project:
  type: website

website:
  title: Documentation
  navbar:
    title: "<span class='fw-lighter text-uppercase'>Documentation</span><br>
    <span class='fw-lighter fs-6'>Base de données de mesures de contaminants sur des oiseaux marins</span>"
    logo: logo.png
  sidebar:
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - deploy.qmd
      - section: "Consolider les données"
        contents:
          - tbl_projects.qmd
          - tbl_sites.qmd
          - tbl_analytes.qmd
          - tbl_measurements.qmd
      - section: "Base de données"
        contents:
          - db_schema.qmd
          - db_feed.qmd
          - db_query.qmd
  repo-url: https://github.com/ECCC-lavoie-ecotox/integration-dbs-docs

format:
  html:
    lang: fr 
    code-overflow: wrap
    page-layout: full
    highlight-style: monokai
    theme: 
      light: flatly
      dark: solar
    code-tools:
      source: true
      toggle: false
      caption: none
    css: styles.css
    toc: true



