project:
  type: website

execute:
  freeze: auto

website:
  title: "Docs"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - projects.qmd
          - measurements.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



