---
title: "Description des contaminants"
author: "Steve Vissault"
date: "2024-01-05"
---

## Otenir une liste exhaustive des contaminants 

On cherche à obtenir une liste exhaustive des contaminants mesurés chez quatre espèces impliquées dans le PASL.

```{R}
contaminants <- toxbox::itgr_measurements()
```

### QA sur les noms de contaminants

Certains noms de composées divergent entre les différents classeurs de données (espèces)

```{R, results="asis"}
dups_contaminants <- contaminants |> 
    dplyr::group_by(conpound_family, variable) |>
    dplyr::arrange(desc(variable)) |>
    dplyr::count()

reactable::reactable(dups_contaminants)
```

Atelier 1: Jouer a pareil, pas pareil, pour consolider la nomenclature des contaminants

### QA sur les noms des sites
 
```{R, results="asis"}
dups_sites <- contaminants |> 
    dplyr::group_by(Location) |>
    dplyr::count()

reactable::reactable(dups_sites)
```

Atelier 2: Jouer a pareil, pas pareil, pour consolider la nomenclature des sites

### QA Data censurées

On applique la transformation avec la fonction `toxbox::uncensored()`.

```{R}
contaminants_uncensored <- contaminants |> 
    toxbox::uncensored(cols = "value", keep_cens = TRUE)
```

Isolation des valeurs NA's pour comprendre quelles sont les mesures qui ne peuvent pas être transformé en valeur numérique. 

#### Q1. Combien de données se retrouvent dans ce cas de figure?

```{R}
table(is.na(contaminants_uncensored$value))
```

#### Q2. Dans quelle classeur et quel onglet on retrouve ces valeurs?

```{R}
contaminants_uncensored |> 
    dplyr::filter(is.na(value)) |>
    dplyr::group_by(source, conpound_family) |>
    dplyr::count() |>
    dplyr::arrange(source) |>
    reactable::reactable()
```

#### Q3. C'est quoi les valeurs qui ne peuvent pas être transférer en valeur numérique (après retrait du symbole <)?

TODO: A compléter ici, marche pas

```{R, eval = FALSE}
contaminants |> 
    dplyr::filter(stringr::str_detect(stringr::str_trim(value), "[:alpha:]")) |>
    as.data.frame() |>
    reactable::reactable()
```
