---
title: "Recensement des sites"
---

On dispose d'une liste de référence des sites avec leurs localisations à cet emplacement `Z:\07-Données BD\intermediate_files\sites_tp20_et_dbs_list_24042024.xlsx`.

Ce fichier est le fruit d'une consolidation manuelle entre les sites documentés dans les onglets "Metadata - entêtes et notes" de plusieurs bases de données du PASL et le fichier TP-20, disposant de liste de choix pré-établie. 

On charge cette table des sites en mémoire.

```{R}
sites_tp20_dbs <- readxl::read_excel("Z:/07-Données BD/intermediate_files/sites_tp20_et_dbs_list_24042024.xlsx")
```

On commence par extraire la liste des sites identifiés dans toutes les bases de données.

```{R}
sites <- toxbox::itgr_measurements() |>
    dplyr::select(location = Location, source) |>
    dplyr::distinct()
```

On effectue un fuzzy join en se basant sur le nom du site.

```{R}
sites_with_locations <- fuzzyjoin::stringdist_left_join(
    sites, 
    sites_tp20_dbs,
    method = "lv"
) |> dplyr::distinct()

# writexl::write_xlsx(sites_with_locations, "Z:/07-Données BD/intermediate_files/site_locations_29042024.xlsx")
```

Après une consolidation manuelle effectuer dans le fichier `Z:/07-Données BD/intermediate_files/site_locations_29042024.xlsx`. 

On peut à présent cartographier les sites pour lesquelles nous disposons d'une localisation.

```{R}
sites <- readxl::read_excel("Z:/07-Données BD/intermediate_files/site_locations_29042024.xlsx")

library(sf)
sites_sf <- sites |>
    dplyr::filter(!is.na(lat) | !is.na(lon)) |> 
    sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

mapview::mapview(sites_sf)
```

